#!/bin/bash
table_header=$1
status=$2
message=$3
if [[ ! -n "${CIRCLE_PR_NUMBER}" ]] ; then
    export CIRCLE_PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | rev | cut -d"/" -f1 | rev)
fi

icon=':no_entry_sign:'
gen_by_icon=':boom:'

if [ "${status}" = "pass" ] ; then
    icon=':white_check_mark:'
    gen_by_icon=':beer:'
fi

curl -X POST -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" --data '{"body": "<table><thead><tr><th width=\"50\"><\/th><th width=\"100%\">'"${table_header}"'<\/th><\/tr><\/thead><tbody><tr><td>'"${icon}"'<\/td><td data-sticky=\"false\">'"${message}"'<\/td><\/tr><\/tbody><\/table><p align=\"right\" data-meta=\"generated_by_danger\">Generated by '"${gen_by_icon}"' <a href=\"https:\/\/circleci.com\/gh\/'"${CIRCLE_PROJECT_USERNAME}"'\/'"${CIRCLE_PROJECT_REPONAME}"'\/\">hike-ci<\/a><\/p>"}' https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}/comments